- name: Add repository
  yum_repository:
    name: wandisco
    description: Wandisco YUM repo
    baseurl: http://opensource.wandisco.com/rhel/$releasever/git/$basearch
    gpgcheck: no

- name: Installs necessary packages
  package: pkg={{ item }} state=latest
  with_items:
    - httpd
    - git
    - curl

- name: Push future default virtual host configuration
  copy: src=cfgmgmtcamp dest=/etc/httpd/conf.d/cfgmgmtcamp.conf mode=0640

- name: Deploy the configuration management camp website
  git: repo=https://github.com/cfgmgmtcamp/cfgmgmtcamp.github.io.git dest=/var/www/cfgmgmtcamp depth=1
  tags: deploy
  notify:
    - restart apache
#- name: Activates the virtualhost
#  command: a2ensite cfgmgmtcamp

- name: Check that the config is valid
  command: apachectl configtest
  register: result
  ignore_errors: True

- name: ensure httpd is enabled and runing
  service: 
    name: httpd 
    state: started 
    enabled: yes
