---
driver:
  name: vagrant

provisioner:
  hosts: all
  name: ansible_playbook
  roles_path: roles
  require_ansible_repo: true
  ansible_verbose: true
  ansible_version: latest
  require_chef_for_busser: false
  playbook:  site.yml

verifier:
  name: inspec
  sudo: true

platforms:
  - name: centos-7
    driver_config:
      network:
      - ['forwarded_port', {guest: 80, host: 8888}]
      - ['private_network', {ip: '192.168.33.11'}]

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
        - my-linux-baseline
